// Ported from journeysnudgesemi/emi-conversions-prototype.html's
// dcConfirmAddNode / dcConfirmEditNode / dcRemoveEdge / dcRemoveRoot /
// dcConfirmConnectExisting / dcReplaceAutoNode — reworked from mutating a
// global `dripWiz` object into a useReducer-compatible pure reducer.
// Every action below clones its input graph once, then runs the same
// mutate-style graph-op functions against that clone — same algorithms,
// new mutation target, per the migration plan.
import type { DripGraph, DripGoal } from '../data/graphTypes';
import type { DcNodeType } from '../data/nodeMeta';
import { DC_EVENT_ENTITY, DC_PROMOTED_ATTR } from '../data/sharedConstants';
import { dcNewEdgeId, dcNewNodeId } from './idGen';
import { dcReconcileBranchEdges, dcRemoveEdge as dcRemoveEdgeOp, dcRemoveGoalCheck as dcRemoveGoalCheckOp, dcRemoveRoot as dcRemoveRootOp } from './graphOps';
import { dcDecisionBranchSummary, dcGoalLabel, dcRecomputeLabelMeta } from './labelMeta';

function cloneGraph(graph: DripGraph): DripGraph {
  return { nodes: structuredClone(graph.nodes), edges: structuredClone(graph.edges), rootId: graph.rootId };
}

// GOAL_CHECK is a real, first-class node type (Phase 1 IA, approved) — not
// a SPLIT with a `_config.basis === 'Goal reached'` flag. A node is a
// Goal Check purely by virtue of its type; there's no meta-string
// matching or `_config` shape to inspect, since it carries no
// configuration of its own at all.
export function dcIsGoalCheckNode(node: { type: string }): boolean {
  return node.type === 'GOAL_CHECK';
}

// Where a new node attaches: the very first node in the campaign, filling
// an existing open slot, growing a brand-new leaf off an existing node, or
// splicing into an edge that already connects two real nodes.
export type DcAddingAt = { kind: 'root' } | { kind: 'edge'; edgeId: string } | { kind: 'growLeaf'; nodeId: string } | { kind: 'midEdge'; edgeId: string };

// Builds the new node (via dcRecomputeLabelMeta, so label/meta logic lives
// in exactly one place, shared with editing), then any type-specific
// auto-children as real graph nodes/edges (a Send's own goal-check, a Wait
// Until's outcome check, a Split's auto Yes-branch, a Random/Decision
// Split's open arms), then attaches the whole thing to whichever
// slot/leaf this add action started from.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function dcConfirmAddNode(graph: DripGraph, type: DcNodeType, p: any, addingAt: DcAddingAt, goal: DripGoal | null): DripGraph {
  const next = cloneGraph(graph);
  const { label, meta } = dcRecomputeLabelMeta(type, p, goal);
  const id = dcNewNodeId();
  next.nodes[id] = { id, type, label, meta, _config: structuredClone(p), autoGenerated: false };

  // Goal check fires after every step that represents either a real send
  // (Send — a fallback channel is still the same send, not a second step)
  // or real time passing (Pause) — not just after a Send. A customer can
  // convert on their own while a campaign is mid-wait, and without a
  // check right after the Pause, the next scheduled action would fire
  // blindly regardless of whether they'd already hit the goal. Wait
  // Until is the one exception — it already has its own real outcome
  // check below, a more precise version of this same idea, not something
  // to layer a second generic check on top of.
  if (type === 'SEND' || type === 'PAUSE') {
    const goalLabel = dcGoalLabel(goal);
    if (goalLabel) {
      const question = goalLabel + '?';
      const checkId = dcNewNodeId();
      const goalId = dcNewNodeId();
      next.nodes[checkId] = { id: checkId, type: 'GOAL_CHECK', label: question, meta: '', _config: null, autoGenerated: true };
      next.nodes[goalId] = { id: goalId, type: 'GOAL_EXIT', label: question.replace(/\?$/, ''), meta: '', _config: null, autoGenerated: true };
      next.edges.push({ id: dcNewEdgeId(), from: id, to: checkId, branchLabel: '', autoGenerated: true });
      next.edges.push({ id: dcNewEdgeId(), from: checkId, to: goalId, branchLabel: 'Yes', autoGenerated: true });
      next.edges.push({ id: dcNewEdgeId(), from: checkId, to: null, branchLabel: 'No', autoGenerated: false });
    } else {
      // No campaign goal defined — there's nothing real to check, so a
      // "Goal?" Split here would just be dead weight with no meaning
      // behind it. Leave a plain open slot for whatever comes next
      // instead.
      next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: '', autoGenerated: false });
    }
  } else if (type === 'WAIT_UNTIL') {
    // The event firing at all is only "success" when it's unambiguous
    // (Card Activated, RP Redeemed). For anything with a real outcome
    // attribute (EMI Request's New Status — Successful/Failed/Expired/
    // Rejected all fire the SAME event), auto-exiting straight to
    // Goal-Based Exit would silently mislabel a Failed resolution as
    // success — auto-insert a real outcome check instead.
    const entity = DC_EVENT_ENTITY[p.eventCategory];
    const statusAttr = DC_PROMOTED_ATTR[entity];
    if (statusAttr) {
      const goalMatchesThisEvent = goal && goal.eventCategory === p.eventCategory && goal.eventType === p.eventType;
      const goalCond = goalMatchesThisEvent ? (goal!.conditions || []).find((c) => c.attribute === statusAttr) : null;
      const splitId = dcNewNodeId();
      if (goalCond) {
        // This IS a genuine check of the one campaign goal (the event just
        // fired matches the goal's own event + the goal's own status
        // condition) — a real GOAL_CHECK, not a generic custom Condition,
        // even though it's phrased in terms of this specific event's
        // status attribute rather than dcGoalLabel's own text.
        next.nodes[splitId] = { id: splitId, type: 'GOAL_CHECK', label: `${statusAttr} = ${goalCond.value}?`, meta: '', _config: null, autoGenerated: true };
        const goalExitId = dcNewNodeId();
        const exitId = dcNewNodeId();
        next.nodes[goalExitId] = { id: goalExitId, type: 'GOAL_EXIT', label: dcGoalLabel(goal)!, meta: '', _config: null, autoGenerated: true };
        next.nodes[exitId] = { id: exitId, type: 'EXIT', label: `Resolved, but not to the goal outcome (${statusAttr} ≠ ${goalCond.value})`, meta: '', _config: null, autoGenerated: false };
        next.edges.push({ id: dcNewEdgeId(), from: id, to: splitId, branchLabel: '', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: goalExitId, branchLabel: 'Yes', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: exitId, branchLabel: 'No', autoGenerated: false });
      } else {
        // Waiting on a multi-outcome event that ISN'T what the Goal is
        // defined against (or no Goal set at all) — no correct default
        // here, so don't guess. Leave both branches open.
        next.nodes[splitId] = { id: splitId, type: 'SPLIT', label: `${statusAttr}?`, meta: 'Define what counts as success for this outcome — not the campaign Goal, so nothing is auto-filled', _config: null, autoGenerated: true };
        next.edges.push({ id: dcNewEdgeId(), from: id, to: splitId, branchLabel: '', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: null, branchLabel: 'Success outcome', autoGenerated: false });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: null, branchLabel: 'Other outcome', autoGenerated: false });
      }
    } else {
      // Unambiguous event (no status attribute at all — "Card Activated"
      // firing only ever means one thing). Still only a real Goal Reached
      // when a campaign Goal is actually defined AND it's specifically
      // this event — same symmetry as the statusAttr branch above. An
      // event firing is never automatically "the goal," regardless of
      // how unambiguous it is, unless a Goal says so.
      const goalMatchesThisEvent = goal && goal.eventCategory === p.eventCategory && goal.eventType === p.eventType;
      if (goalMatchesThisEvent) {
        const goalExitId = dcNewNodeId();
        next.nodes[goalExitId] = { id: goalExitId, type: 'GOAL_EXIT', label, meta: '', _config: null, autoGenerated: true };
        next.edges.push({ id: dcNewEdgeId(), from: id, to: goalExitId, branchLabel: 'Yes', autoGenerated: true });
      } else {
        next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'Yes', autoGenerated: false });
      }
    }
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'No', autoGenerated: false });
  } else if (type === 'SPLIT') {
    // A user-built Condition asks "does the customer satisfy these
    // conditions?" — it has no built-in relationship to the campaign
    // goal, so unlike GOAL_CHECK it never auto-wires a Yes branch to
    // Goal Reached. Both arms are left open; if "this branch means the
    // goal was achieved" is genuinely what's meant, Goal Reached is
    // still available to add manually on either arm (§5/§10A — disabled
    // elsewhere in the taxonomy, but enabled here, since this is exactly
    // the already-forked branch-arm context that's meant for).
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'Yes', autoGenerated: false });
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'No', autoGenerated: false });
  } else if (type === 'DECISION_SPLIT') {
    // One open edge per real branch, evaluated top-to-bottom on the canvas
    // the same order they're listed here, plus one final fixed "Anything
    // else" catch-all edge.
    p.branches.forEach((b: { id?: string; label: string }) => {
      next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: `${b.label} (${dcDecisionBranchSummary(p, b as never)})`, branchId: b.id, autoGenerated: false });
    });
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'Anything else', autoGenerated: false });
  } else if (type === 'RANDOM_SPLIT') {
    p.branches.forEach((b: { id?: string; label: string; pct: number }) => {
      next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: `${b.label} (${b.pct}%)`, branchId: b.id, autoGenerated: false });
    });
  }

  if (addingAt.kind === 'root') next.rootId = id;
  else if (addingAt.kind === 'edge') {
    const e = next.edges.find((e) => e.id === addingAt.edgeId);
    if (e) e.to = id;
  } else if (addingAt.kind === 'growLeaf') {
    next.edges.push({ id: dcNewEdgeId(), from: addingAt.nodeId, to: id, branchLabel: '', autoGenerated: false });
  } else if (addingAt.kind === 'midEdge') {
    // Splice the new node into an edge that already connects two real
    // nodes — the edge now points at the new node instead of its original
    // target, and whatever the new node's own auto-children left open gets
    // reattached to that original target, so the rest of the chain is
    // never lost. Only safe when the new node (plus its auto-children)
    // left exactly ONE dangling continuation edge — a branching type
    // (Random/Decision Split) leaves several open arms with no single
    // correct one to reattach, so the UI restricts which types are
    // offered for a midEdge insert to the single-continuation ones
    // (Send, Pause, Wait Until, Conditional Split) —
    // this is defensive, not the primary guard.
    const e = next.edges.find((e) => e.id === addingAt.edgeId);
    if (e && e.to) {
      const originalTarget = e.to;
      e.to = id;
      const reachable = new Set<string>([id]);
      const queue = [id];
      while (queue.length) {
        const cur = queue.shift()!;
        next.edges.filter((e2) => e2.from === cur && e2.to).forEach((e2) => {
          if (!reachable.has(e2.to!)) {
            reachable.add(e2.to!);
            queue.push(e2.to!);
          }
        });
      }
      const openEdges = next.edges.filter((e2) => reachable.has(e2.from) && e2.to === null);
      if (openEdges.length === 1) openEdges[0].to = originalTarget;
    }
  }

  return next;
}

// Recomputes only label+meta for an existing node's new config and
// reconciles branch edges where relevant — never touches unrelated
// children. Editing must never regenerate a subtree; whatever's already
// built under a node stays exactly as it was.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function dcConfirmEditNode(graph: DripGraph, nodeId: string, type: DcNodeType, p: any, goal: DripGoal | null): DripGraph {
  const next = cloneGraph(graph);
  const node = next.nodes[nodeId];
  if (!node) return next;
  const { label, meta } = dcRecomputeLabelMeta(type, p, goal);
  node.label = label;
  node.meta = meta;
  node._config = structuredClone(p);

  // Random Split / Decision Split branches are real outgoing edges —
  // whatever's been built under each arm must survive an edit, including
  // one that adds, removes, or inserts a branch in the middle.
  if (type === 'RANDOM_SPLIT') {
    dcReconcileBranchEdges(next, nodeId, p.branches, (b) => `${(b as { label: string }).label} (${(b as { pct: number }).pct}%)`, null);
  }
  if (type === 'DECISION_SPLIT') {
    dcReconcileBranchEdges(next, nodeId, p.branches, (b) => `${(b as { label: string }).label} (${dcDecisionBranchSummary(p, b as never)})`, 'Anything else');
  }

  // Unlike the old model, a user-built Condition (SPLIT) never auto-wires
  // its Yes branch to Goal Reached (see dcConfirmAddNode) — there's no
  // stale auto-exit to reconcile here when its condition changes. GOAL_CHECK
  // nodes (the ones that DO always mean "the campaign goal") are never
  // edited through this path at all — they carry no configuration, so
  // there's nothing for a form to submit in the first place.

  return next;
}

export function dcRemoveEdge(graph: DripGraph, edgeId: string): DripGraph {
  const next = cloneGraph(graph);
  dcRemoveEdgeOp(next, edgeId);
  return next;
}

export function dcRemoveRoot(graph: DripGraph): DripGraph {
  const next = cloneGraph(graph);
  dcRemoveRootOp(next);
  return next;
}

export function dcRemoveGoalCheck(graph: DripGraph, splitNodeId: string): DripGraph {
  const next = cloneGraph(graph);
  dcRemoveGoalCheckOp(next, splitNodeId);
  return next;
}
